package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/harsimranman/accounting/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Expense)
// DB Table: Plural (expenses)
// Resource: Plural (Expenses)
// Path: Plural (/expenses)
// View Template Folder: Plural (/templates/expenses/)

// ExpensesResource is the resource for the Expense model
type ExpensesResource struct {
	buffalo.Resource
}

// List gets all Expenses. This function is mapped to the path
// GET /expenses
func (v ExpensesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	expenses := &models.Expenses{}
	cid := (c.Value("currentUser").(*models.User)).CompanyID
	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Expenses from the DB
	if err := q.Where("company_id = ?", cid).All(expenses); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, expenses))
}

// Show gets the data for one Expense. This function is mapped to
// the path GET /expenses/{expense_id}
func (v ExpensesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Expense
	expense := &models.Expense{}
	cid := (c.Value("currentUser").(*models.User)).CompanyID

	// To find the Expense the parameter expense_id is used.
	if err := tx.Where("company_id = ?", cid).Find(expense, c.Param("expense_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, expense))
}

// New renders the form for creating a new Expense.
// This function is mapped to the path GET /expenses/new
func (v ExpensesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Expense{}))
}

// Create adds a Expense to the DB. This function is mapped to the
// path POST /expenses
func (v ExpensesResource) Create(c buffalo.Context) error {
	// Allocate an empty Expense
	expense := &models.Expense{}

	// Bind expense to the html form elements
	if err := c.Bind(expense); err != nil {
		return errors.WithStack(err)
	}
	expense.CompanyID= (c.Value("currentUser").(*models.User)).CompanyID
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(expense)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, expense))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Expense was created successfully")

	// and redirect to the expenses index page
	return c.Render(201, r.Auto(c, expense))
}

// Edit renders a edit form for a Expense. This function is
// mapped to the path GET /expenses/{expense_id}/edit
func (v ExpensesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Expense
	expense := &models.Expense{}
	cid := (c.Value("currentUser").(*models.User)).CompanyID

	if err := tx.Where("company_id = ?", cid).Find(expense, c.Param("expense_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, expense))
}

// Update changes a Expense in the DB. This function is mapped to
// the path PUT /expenses/{expense_id}
func (v ExpensesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Expense
	expense := &models.Expense{}

	cid := (c.Value("currentUser").(*models.User)).CompanyID
	if err := tx.Where("company_id = ?", cid).Find(expense, c.Param("expense_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Expense to the html form elements
	if err := c.Bind(expense); err != nil {
		return errors.WithStack(err)
	}
	expense.CompanyID = cid
	verrs, err := tx.ValidateAndUpdate(expense)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, expense))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Expense was updated successfully")

	// and redirect to the expenses index page
	return c.Render(200, r.Auto(c, expense))
}

// Destroy deletes a Expense from the DB. This function is mapped
// to the path DELETE /expenses/{expense_id}
func (v ExpensesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}
	cid := (c.Value("currentUser").(*models.User)).CompanyID

	// Allocate an empty Expense
	expense := &models.Expense{}

	// To find the Expense the parameter expense_id is used.
	if err := tx.Where("company_id = ?", cid).Find(expense, c.Param("expense_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(expense); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Expense was destroyed successfully")

	// Redirect to the expenses index page
	return c.Render(200, r.Auto(c, expense))
}
