package actions

import (
	"github.com/harsimranman/accounting/models"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (GroupMember)
// DB Table: Plural (group_members)
// Resource: Plural (GroupMembers)
// Path: Plural (/group_members)
// View Template Folder: Plural (/templates/group_members/)

// GroupMembersResource is the resource for the GroupMember model
type GroupMembersResource struct {
	buffalo.Resource
}

// List gets all GroupMembers. This function is mapped to the path
// GET /group_members
func (v GroupMembersResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	groupMembers := &models.GroupMembers{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all GroupMembers from the DB
	if err := q.All(groupMembers); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, groupMembers))
}

// Show gets the data for one GroupMember. This function is mapped to
// the path GET /group_members/{group_member_id}
func (v GroupMembersResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty GroupMember
	groupMember := &models.GroupMember{}

	// To find the GroupMember the parameter group_member_id is used.
	if err := tx.Find(groupMember, c.Param("group_member_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, groupMember))
}

// New renders the form for creating a new GroupMember.
// This function is mapped to the path GET /group_members/new
func (v GroupMembersResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.GroupMember{}))
}

// Create adds a GroupMember to the DB. This function is mapped to the
// path POST /group_members
func (v GroupMembersResource) Create(c buffalo.Context) error {
	// Allocate an empty GroupMember
	groupMember := &models.GroupMember{}

	// Bind groupMember to the html form elements
	if err := c.Bind(groupMember); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(groupMember)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, groupMember))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "GroupMember was created successfully")

	// and redirect to the group_members index page
	return c.Render(201, r.Auto(c, groupMember))
}

// Edit renders a edit form for a GroupMember. This function is
// mapped to the path GET /group_members/{group_member_id}/edit
func (v GroupMembersResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty GroupMember
	groupMember := &models.GroupMember{}

	if err := tx.Find(groupMember, c.Param("group_member_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, groupMember))
}

// Update changes a GroupMember in the DB. This function is mapped to
// the path PUT /group_members/{group_member_id}
func (v GroupMembersResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty GroupMember
	groupMember := &models.GroupMember{}

	if err := tx.Find(groupMember, c.Param("group_member_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind GroupMember to the html form elements
	if err := c.Bind(groupMember); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(groupMember)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, groupMember))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "GroupMember was updated successfully")

	// and redirect to the group_members index page
	return c.Render(200, r.Auto(c, groupMember))
}

// Destroy deletes a GroupMember from the DB. This function is mapped
// to the path DELETE /group_members/{group_member_id}
func (v GroupMembersResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty GroupMember
	groupMember := &models.GroupMember{}

	// To find the GroupMember the parameter group_member_id is used.
	if err := tx.Find(groupMember, c.Param("group_member_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(groupMember); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "GroupMember was destroyed successfully")

	// Redirect to the group_members index page
	return c.Render(200, r.Auto(c, groupMember))
}
